### ISSUE TITLE
failed to load swrast driver & DISALLOWED_INTENTS

### ISSUE THREAD

**Issue by InfinityRed-Code** [Smiche/MMM-DiscordWatch#5]
I installed the module exactly point for point like showedin the description, but when I start it, it just says "No Messages"
The Terminal shows two Messages:

1. 
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:\$${ORIGIN}/dri:/usr/lib/dri)
failed to load swrast drive

2.
 Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/pi/Documents/MagicMirror/modules/MMM-DiscordWatch/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at async Client.login (/home/pi/Documents/MagicMirror/modules/MMM-DiscordWatch/node_modules/discord.js/src/client/Client.js:254:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}

I am running the Mirror on a Raspberry Pi 4B with the legacy OS as it seems to work better with most other modules, Everything is up to date and I even tried to install the drivers and utility afterwards.

The Discord Bot is offline the whole time btw. I have no Idea if this is supposed to be that way or how I get it on.

Would apreciate some help

**Comment by wolflu05** [comment]
Discord has some Intent system, which you manually need to activate in order to receive events for new messages. You can read more about it [here](https://discordjs.guide/popular-topics/intents.html#privileged-intents). Enabeling the last switch should get your bot working:
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/76838159/179989455-609b8ea0-8edc-42eb-a70f-00dcc0353cbf.png">

**Comment by InfinityRed-Code** [comment]
I turned everything on and played around with it. The same Errors keep coming up. Both, the driver error and disallowed intend

**Comment by wolflu05** [comment]
Then there are some changes on the code needed.

**Comment by InfinityRed-Code** [comment]
A combination of installing the Magic Mirror on the non legacy RaspberryPiOS, dis- and then reenabeling all the "privileged gateway intents" switches, resetting the token and using the ID of a newly created channel got it to work. Did not have to change the code.

**Comment by wolflu05** [comment]
ok. Great that it works now.
